In [1]:
'''
The core data type in Numpy is the ndarray, which enables fast and space-efficient multidimensional array processing.
Note: This notebook is adapted from chapter 4 Python for Data Analysis by Wes McKinney and O'Reilly publishing. NumPy has many, 
many features that won't be covered here. The following snippets are just to illustrate basic data types and operations within
numpy.

Another good resource for learning more about ndarrays is here:
http://docs.scipy.org/doc/numpy/reference/arrays.html
'''

#First, import NumPy
import numpy as np

#It is easy to create Nx1 and NxM arrays from standard Python lists
l1 = [0,1,2]
l2 = [3,4,5]

nd1 = np.array(l1)
nd2 = np.array([l1,  l2])

In [2]:
#Now, we can get ask for some basic info to describe the ndarray
def desc_ndarray(nd):
    try:
        print("The ndarray has dimension n=%s and m=%s" % (nd.shape[0],nd.shape[1]))
    except:
        print("The ndarray has dimension n=%s and m=1" % nd.shape[0])
    print("The ndarray has elements of type=%s" % nd.dtype)

desc_ndarray(nd1)

desc_ndarray(nd2)



The ndarray has dimension n=3 and m=1
The ndarray has elements of type=int32
The ndarray has dimension n=2 and m=3
The ndarray has elements of type=int32


In [3]:
#There are short cuts for creating certain frequently used special ndarrays, i.e.,

k=4

#1. an ndarray of all zeros
zero = np.zeros(k)

#2. an ndarray of all ones
one = np.ones(k)

#3. an ndarray of random elements (this one is standard normal, but there are many distributions to choose from)
rand = np.random.randn(k)

[zero, one, rand]

[array([ 0.,  0.,  0.,  0.]),
 array([ 1.,  1.,  1.,  1.]),
 array([ 0.25694225,  0.23548643,  0.01881724, -1.19394458])]

In [4]:
'''
For indexing an array:
1. If nx1 array, follow the same protocol as a regular Python list
2. If nxm array use the following examples
'''

arr2d = np.random.randn(4,2)

#A single index gets a full row

#2 indexes returns a value
[arr2d, arr2d[1],  arr2d[1,1]]

[array([[-0.43663071, -0.96005209],
        [-0.76865575,  0.66679101],
        [ 0.35752326, -1.22032162],
        [ 0.0202129 , -0.96661321]]),
 array([-0.76865575,  0.66679101]),
 0.66679101186745593]

In [5]:
'''
Operations between Arrays and Scalars
An important feature of ndarrays is they allow batch operations on data without writing any for loops.  
This is called vectorization.
Any arithmetic operations between equal-size arrays applies the operation elementwise. 
'''

#examples

k = 4
rand = np.random.randn(k)
[rand, rand + rand, 2*rand, rand*np.zeros(4)]



[array([-0.9355633 ,  0.29723855, -0.20369969,  0.02445605]),
 array([-1.8711266 ,  0.59447709, -0.40739938,  0.04891209]),
 array([-1.8711266 ,  0.59447709, -0.40739938,  0.04891209]),
 array([-0.,  0., -0.,  0.])]

In [6]:
'''
Matrix operations
It is easy to do matrix operations with Nd arrays. The standard arithmetic operators don't work here though. And it is important 
to make sure matrix shapes are compatible
'''

k = 3
r1 = np.random.randn(k)
r2 = np.random.randn(k)

#Matrix addition is the standard matrix operator
[r1, r2 , r1 + r2]


[array([ 0.66892705, -1.96395363, -0.1137587 ]),
 array([-0.28063127, -1.568189  ,  0.41420961]),
 array([ 0.38829578, -3.53214264,  0.30045091])]

In [7]:
#The Transpose can be taken with the attribute T
arr2d = np.array([r1, r2])
[arr2d, arr2d.T]

[array([[ 0.66892705, -1.96395363, -0.1137587 ],
        [-0.28063127, -1.568189  ,  0.41420961]]),
 array([[ 0.66892705, -0.28063127],
        [-1.96395363, -1.568189  ],
        [-0.1137587 ,  0.41420961]])]

In [8]:
'''
Matrix multiplication, like inner products can be done on arrays.
Just remember that the standard multiplication operator does elementwise multiplication (provided they are the same shape).
We need the dot method in order to do an inner product

Numpy has a linalg library that can run most matrix operations on ndarrays:
http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

One can also create a matrix object and use the methods in numpy.matrix to achieve the same thing:
http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html
'''

[arr2d, arr2d * arr2d, arr2d.dot(arr2d.T)]

[array([[ 0.66892705, -1.96395363, -0.1137587 ],
        [-0.28063127, -1.568189  ,  0.41420961]]),
 array([[ 0.4474634 ,  3.85711387,  0.01294104],
        [ 0.07875391,  2.45921675,  0.1715696 ]]),
 array([[ 4.31751831,  2.8450087 ],
        [ 2.8450087 ,  2.70954026]])]

In [9]:
'''
One important feature of vectorization is that it allows elementwise processing that is much faster than writing a traditional
loop.
'''
import math

#show an example and profile i
%timeit [math.sqrt(x) for x in range(1000)]

10000 loops, best of 3: 189 µs per loop


In [10]:
%timeit np.sqrt(np.arange(1000))

The slowest run took 34.56 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.7 µs per loop


In [11]:
'''
The last thing we'll cover in this module is the numpy.random library. In general, it is advised to use numpy for
random number generation as opposed to python's built in random module.

Random number generation has many uses. One common use is generating fake (i.e. random) data to test modeling procedures
or to do Monte Carlo Simulations
'''
import matplotlib.pyplot as plt


In [12]:


#Generate random pairs that have a multivariate normal distribution
N = 1000
mu = np.array([0,0])
cov = 0.5
sig = np.array([[1, cov],[cov, 1]]) #Must be square, symmetric and non-negative definite

In [13]:
x, y = np.random.multivariate_normal(mu, sig, N).T


In [14]:

#Now let's plot and see what that looks like


plt.plot(x, y,'x'); plt.axis('equal'); plt.show()



In [15]:
'''
One final example (taken from Wes Mckinney's book):

Let's generate a random walk and visualize it
'''
import matplotlib.pyplot as plt

nsteps = 1000
draws = np.random.randint(0, 2, size = nsteps) #Randint let's us generate random integers in a range
steps = np.where(draws>0, 1, -1) #there function let's us do boolean logic on a conditional applied to an entire array
walk = steps.cumsum() #Cumsum returns an array with the same size as steps, that has cum sum of steps up to index i
plt.plot(np.arange(len(walk)), walk);plt.show()